replicaCount: 2

persistentVolume:
  enabled: false

tolerations:
  enabled: true
nodeSelector:
  enabled: true
server:
  monitor: false
  imagePullSecrets:
    enabled: true
  resources:
    limits:
      cpu: 1500m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 512Mi

ingress:
  enabled: true
  openPod: false
  annotations:
    kubernetes.io/ingress.class: nginx
  other:
  - name: webapp.startimestv.com
    path:
      - /
  - name: webapp-cdn-source.startimestv.com
    path:
      - /
